ID-514 CTRTrivialPredictor : добавить учет категорий креативов
yoori/rtbserver_cobrazz pull request #10
Opened 2024-08-14 10:14 UTC by arbogdanov

2024-08-15 09:12 UTC, yoori requested changes

2024-08-15 09:12 UTC, yoori commented on PredictorSvcs/BidCostPredictor/BidCostCollector.cpp
> +    file >> tag_id
Важный момент : мы считываем фалй подобного типа построчно, это позволяет избежать неявных проблем если чтение поедет на следующую строку при изменении входного формата (добавление полей и т п). Тут либо istringstream для каждой строки (важно конролировать bad, fail после чтения значений) либо TabInputArchive - он предпочтительнее по производительности

2024-08-15 09:17 UTC, arbogdanov commented on PredictorSvcs/BidCostPredictor/BidCostCollector.cpp
> +    file >> tag_id
Там этот момент проверяется     if (!file)
    {
      clear();

      Stream::Error stream;
      stream << FNS
             << "Error reading file="
             << path
             << ", line="
             << line;
      throw Exception(stream);
    }

2024-08-15 09:19 UTC, arbogdanov commented on PredictorSvcs/BidCostPredictor/BidCostCollector.cpp
> +    file >> tag_id
Преимущества в скорости не будет

2024-08-15 12:03 UTC, yoori approved these changes

2024-09-06 07:38 UTC, yoori approved these changes

2024-09-06 07:58 UTC, closed without merging