ID-522. Add metrics to PubPixelFrontend
yoori/rtbserver_cobrazz pull request #11
Opened 2024-09-04 15:48 UTC by kabulov

2024-09-04 16:30 UTC, yoori requested changes

2024-09-04 16:30 UTC, yoori commented on Frontends/FCGIServer/FCGIServer.cpp
> +      auto pubpixel_frontend_counter_statistics_provider =
Очень плохое место для упоминания конкретных модулей запускаемых в рамках FCGI
В модуль PubPixel должен передаваться CompositeStatisticsProvider и модуль при создании должен регистрироваться в CompositeStatisticsProvider

2024-09-04 16:40 UTC, kabulov commented on Frontends/FCGIServer/FCGIServer.cpp
> +      auto pubpixel_frontend_counter_statistics_provider =
означает ли это, что time_statistics_provider и common_counter_statistics_provider тоже должны быть перенесены ? я по образу и подобию делал

2024-09-06 08:17 UTC, arbogdanov commented on Frontends/FCGIServer/FCGIServer.cpp
> +      auto pubpixel_frontend_counter_statistics_provider =
pubpixel_frontend_counter_statistics_provider - вообще ненужно. Там же общая тема. Т.е.  common_counter_statistics_provider - достаточно. Только нужно сои ID добавить и названия.

2024-09-06 08:19 UTC, arbogdanov commented on Frontends/FrontendCommons/Statistics.hpp
> +class PubPixelFrontendStatisticIdConverter final
Это тоже ненужно. Тут уже имеется common_counter.

2024-09-06 08:21 UTC, arbogdanov commented on Frontends/FrontendCommons/Statistics.hpp
> +enum class PubPixelFrontendStatisticId
Этого ненужно. Там общая тема

2024-12-18 11:05 UTC, closed without merging